# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BTVGGz0_VP7DtxmxMF_TKJ2IWBvNZ_1f
"""

# 定義變換
transforms_dict = {
    "Original Image": None,
    "Resized": transforms.Resize((1080, 900)),
    "Center Cropped": transforms.CenterCrop(400),
    "Color Jittered": transforms.ColorJitter(brightness=0.5, contrast=0.5, saturation=0.5),
    "Horizontally Flipped": transforms.RandomHorizontalFlip(p=1),
    "Randomly Rotated": transforms.RandomRotation(50)
}

# 加載圖片
img_url = 'https://d1grca2t3zpuug.cloudfront.net/2020/10/sekaineko012.jpg'